# Generated by Django 3.2.8 on 2021-11-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0003_alter_superhero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='image',
        ),
    ]
